In [2]:
import numpy as np
import pandas as pd

C:\Users\okeefelab\AppData\Local\Temp\ipykernel_16944\3269992828.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [14]:
"""To find the first insance of STart analysis and check if there is one"""
basepath = 'G:/Angela/Light-dark_box/downsampled_videos/'

import os
os.listdir(basepath)
directory = os.listdir(basepath)

annotpath = []
for i, ii in enumerate(directory):
    if ii[-3:] == 'npy':
        annotpath = np.append(annotpath, os.path.join(basepath, ii))  # this is to append the list with all the videos
        annotpath_list = annotpath.tolist()

for f, ff in enumerate(annotpath_list):
    annot = np.load(annotpath_list[f])
    startidx = np.where(annot == 'Start Analysis')[0][0]
    print(ff, startidx)

G:/Angela/Light-dark_box/downsampled_videos/1118777_LightDarkBox_20230922_125532654downsampled_annotation_set3.npy 130
G:/Angela/Light-dark_box/downsampled_videos/1118778_LightDarkBox_20230922_131224482downsampled_annotation_set3.npy 101
G:/Angela/Light-dark_box/downsampled_videos/1118779_LightDarkBox_20230922_132506666downsampled_annotation_set3.npy 109
G:/Angela/Light-dark_box/downsampled_videos/1118780_LightDarkBox_20230922_135148511downsampled_annotation_set3.npy 111
G:/Angela/Light-dark_box/downsampled_videos/1118781_LightDarkBox_20230922_133905089downsampled_annotation_set3.npy 128
G:/Angela/Light-dark_box/downsampled_videos/1118783_LightDarkBox_20230922_145053622downsampled_annotation_set3.npy 117
G:/Angela/Light-dark_box/downsampled_videos/1118784_LightDarkBox_20230922_150552834downsampled_annotation_set3.npy 121
G:/Angela/Light-dark_box/downsampled_videos/1118785_LightDarkBox_20230922_151852024downsampled_annotation_set3.npy 124
G:/Angela/Light-dark_box/downsampled_videos/1118786_LightDarkBox_20230922_153140038downsampled_annotation_set3.npy 116
G:/Angela/Light-dark_box/downsampled_videos/1118786_Second_LightDarkBox_20230922_153730486downsampled_annotation_set3.npy 0
G:/Angela/Light-dark_box/downsampled_videos/1118787_LightDarkBox_20230922_154756153downsampled_annotation_set3.npy 132
G:/Angela/Light-dark_box/downsampled_videos/1118790_LightDarkBox_20230922_140542869downsampled_annotation_set3.npy 119
G:/Angela/Light-dark_box/downsampled_videos/1118791_LightDarkBox_20230922_143516429downsampled_annotation_set3.npy 132
G:/Angela/Light-dark_box/downsampled_videos/1118793_LightDarkBox_20230922_163301885downsampled_annotation_set3.npy 118
G:/Angela/Light-dark_box/downsampled_videos/1118794_LightDarkBox_20230922_164545638downsampled_annotation_set3.npy 115
G:/Angela/Light-dark_box/downsampled_videos/1118795_LightDarkBox_20230922_165758380downsampled_annotation_set3.npy 101
G:/Angela/Light-dark_box/downsampled_videos/1118796_LightDarkBox_20230922_171039708downsampled_annotation_set3.npy 108
G:/Angela/Light-dark_box/downsampled_videos/1118881_Light-dark_box_20231006_151209983downsampled_annotation_set3.npy 129
G:/Angela/Light-dark_box/downsampled_videos/1118882_Light-dark_box_20231006_152502926downsampled_annotation_set3.npy 154
G:/Angela/Light-dark_box/downsampled_videos/1118883_Light-dark_box_20231006_145910220downsampled_annotation_set3.npy 133
G:/Angela/Light-dark_box/downsampled_videos/1119001_light-dark_box_20231026_153024319downsampled_annotation_set3.npy 161
G:/Angela/Light-dark_box/downsampled_videos/1119002_light-dark_box_20231030_102458042downsampled_annotation_set3.npy 151
G:/Angela/Light-dark_box/downsampled_videos/1119036_light-dark_box_20231030_113119910downsampled_annotation_set3.npy 142
G:/Angela/Light-dark_box/downsampled_videos/1119037_light-dark_box_20231030_110456567downsampled_annotation_set3.npy 154
G:/Angela/Light-dark_box/downsampled_videos/1119038_light-dark_box_20231030_111834677downsampled_annotation_set3.npy 142
G:/Angela/Light-dark_box/downsampled_videos/1119039_light-dark_box_20231030_105148130downsampled_annotation_set3.npy 144
G:/Angela/Light-dark_box/downsampled_videos/1119040_light-dark_box_20231030_114508219downsampled_annotation_set3.npy 148
G:/Angela/Light-dark_box/downsampled_videos/1119041_light-dark_box_20231030_115840402downsampled_annotation_set3.npy 152
G:/Angela/Light-dark_box/downsampled_videos/1119042_light-dark_box_20231030_121144556downsampled_annotation_set3.npy 185
G:/Angela/Light-dark_box/downsampled_videos/1119050_light-dark_box_20231030_103823635downsampled_annotation_set3.npy 142
G:/Angela/Light-dark_box/downsampled_videos/1119060_light-dark_box_20231030_122437222downsampled_annotation_set3.npy 138
G:/Angela/Light-dark_box/downsampled_videos/1119143_light-dark_box_20231120_104745557downsampled_annotation_set3.npy 154
G:/Angela/Light-dark_box/downsampled_videos/1119631_LightDarkBox_20230811_142233939downsampled_annotation_set3.npy 110
G:/Angela/Light-dark_box/downsampled_videos/1119632_LightDarkBox_20230811_122730307downsampled_annotation_set3.npy 115
G:/Angela/Light-dark_box/downsampled_videos/1119633_LightDarkBox_20230811_124022173downsampled_annotation_set3.npy 122
G:/Angela/Light-dark_box/downsampled_videos/1119636_LightDarkBox_20230811_150125724downsampled_annotation_set3.npy 109
G:/Angela/Light-dark_box/downsampled_videos/1119637_LightDarkBox_20230811_151500157downsampled_annotation_set3.npy 120
G:/Angela/Light-dark_box/downsampled_videos/1119663_LightDarkBox_20230811_111801893downsampled_annotation_set3.npy 143
G:/Angela/Light-dark_box/downsampled_videos/1119723_LightDarkBox_20230811_144859539downsampled_annotation_set3.npy 108
G:/Angela/Light-dark_box/downsampled_videos/1119724_LightDarkBox_20230811_152750589downsampled_annotation_set3.npy 122

In [3]:
test=np.load('/Users/loukia/Desktop/LocatioAnalysis/Loc_15/TrackingData/1119050_20231020_Loc_15_mousecoordx.npy')
print(test.shape)
print(type(test))
print(test)

(8, 18192)
<class 'numpy.ndarray'>
[[ 34.56  33.34  31.77 ... 504.2  504.2  504.2 ]
 [ 37.9   37.53  37.53 ... 522.5  522.5  522.5 ]
 [ 51.47  49.    47.6  ... 506.2  506.2  506.2 ]
 ...
 [ 86.8   79.06  74.8  ... 509.5  509.   508.  ]
 [   nan 101.8  101.8  ... 541.5  537.5  530.5 ]
 [   nan    nan    nan ... 467.   467.   467.  ]]

In [ ]:
test2=np.load('F:Analysis_M1115859_20210415/kilosortData/templates.npy')
print(test2.shape)
print(type(test2))
print(test2)

In [3]:
test3 = np.load(r'G:\Angela\Y-maze\Results_OG\YMazeResults.npy', allow_pickle=True)

print(test3)
df = pd.DataFrame(test3)
df

[['MouseID' 'Date' 'Genotype' ... 'SameArmReturn_num'
  'AlternateArmReturn_num' '%Alternation']
 ['1119565' '20230720' 'wt' ... 6.0 11.0 52.77777777777778]
 ['1119628' '20230720' 'NLGF' ... 5.0 15.0 52.5]
 ...
 ['1119788' '20240116' 'wt' ... 2.0 3.0 70.58823529411765]
 ['1119789' '20240116' 'wt' ... 0.0 6.0 70.0]
 ['1119794' '20240116' 'wt' ... 0.0 9.0 70.0]]

,0,1,2,3,4,5,6,7,8,9
0,MouseID,Date,Genotype,Gender,Cohort,ArmEntries_num,SpontaneousAlternation_num,SameArmReturn_num,AlternateArmReturn_num,%Alternation
1,1119565,20230720,wt,F,summer,38.0,19.0,6.0,11.0,52.777778
2,1119628,20230720,NLGF,F,summer,42.0,21.0,5.0,15.0,52.5
3,1119630,20230720,wt,F,summer,54.0,24.0,4.0,24.0,46.153846
4,1119631,20230720,NLGF,F,summer,40.0,18.0,9.0,11.0,47.368421
...,...,...,...,...,...,...,...,...,...,...
99,1119741,20240116,wt,f,7,43.0,28.0,0.0,13.0,68.292683
100,1119743,20240116,wt,f,7,35.0,21.0,2.0,10.0,63.636364
101,1119788,20240116,wt,m,7,19.0,12.0,2.0,3.0,70.588235
102,1119789,20240116,wt,m,7,22.0,14.0,0.0,6.0,70.0
103,1119794,20240116,wt,f,7,32.0,21.0,0.0,9.0,70.0

In [7]:
test3 = np.load(r'G:\Angela\light-dark_box\TrackingData\1120807_20240624_light-dark_box_boxcoord.npy', allow_pickle=True)

print(test3)
df = pd.DataFrame(test3)
df

[[485. 171.]
 [783. 168.]
 [781. 775.]
 [485. 779.]]

       0      1
0  485.0  171.0
1  783.0  168.0
2  781.0  775.0
3  485.0  779.0

In [6]:
test4 = np.load('G:/Angela/Y-maze/TrackingData/1118777_20230914_Y-maze_mousecoordx.npy', allow_pickle=True)

# Convert the NumPy array to a pandas DataFrame
df = pd.DataFrame(test4)

# Display information about the DataFrame
print("DataFrame Shape:", df.shape)
print("DataFrame Info:")
print(df.info())

# Display the first few rows of the DataFrame
print("First Few Rows of DataFrame:")
print(df.head())

DataFrame Shape: (8, 14572)
DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Columns: 14572 entries, 0 to 14571
dtypes: float16(14572)
memory usage: 227.8 KB
None
First Few Rows of DataFrame:
    0       1       2       3       4       5       6       7       8      \
0     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
1  1006.0  1008.0  1008.5  1008.5  1008.5  1008.0  1008.0  1007.5  1007.5
2   995.5   996.0   996.5   996.0   996.0   994.5   994.0   994.0   994.0
3   980.5   980.5   980.5   980.5   980.5   980.0   979.5   979.5   979.5
4     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

    9      ...  14562  14563  14564  14565  14566  14567   14568  14569  \
0     NaN  ...  517.0  517.0  517.0  517.0  517.0  517.0  517.00  517.0
1  1007.5  ...  531.5  527.5  525.5  521.0  516.5  512.5  507.25  506.5
2   994.0  ...  517.0  517.0  517.0  517.0  517.0  517.0  517.00  517.0
3   979.5  ...  543.5  543.5  543.5  540.0  538.5  536.0  532.00  531.0
4     NaN  ...  552.5  552.0  551.5  548.0  546.5  544.5  543.50  540.0

   14570  14571
0  517.0  517.0
1  499.0  499.0
2  517.0  517.0
3  525.5  525.5
4  533.0  533.0

[5 rows x 14572 columns]