In [2]:
import numpy as np
import pandas as pd

C:\Users\okeefelab\AppData\Local\Temp\ipykernel_17776\3269992828.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [14]:
"""To find the first insance of STart analysis and check if there is one"""
basepath = 'G:/Angela/Light-dark_box/downsampled_videos/'

import os
os.listdir(basepath)
directory = os.listdir(basepath)

annotpath = []
for i, ii in enumerate(directory):
    if ii[-3:] == 'npy':
        annotpath = np.append(annotpath, os.path.join(basepath, ii))  # this is to append the list with all the videos
        annotpath_list = annotpath.tolist()

for f, ff in enumerate(annotpath_list):
    annot = np.load(annotpath_list[f])
    startidx = np.where(annot == 'Start Analysis')[0][0]
    print(ff, startidx)

G:/Angela/Light-dark_box/downsampled_videos/1118777_LightDarkBox_20230922_125532654downsampled_annotation_set3.npy 130
G:/Angela/Light-dark_box/downsampled_videos/1118778_LightDarkBox_20230922_131224482downsampled_annotation_set3.npy 101
G:/Angela/Light-dark_box/downsampled_videos/1118779_LightDarkBox_20230922_132506666downsampled_annotation_set3.npy 109
G:/Angela/Light-dark_box/downsampled_videos/1118780_LightDarkBox_20230922_135148511downsampled_annotation_set3.npy 111
G:/Angela/Light-dark_box/downsampled_videos/1118781_LightDarkBox_20230922_133905089downsampled_annotation_set3.npy 128
G:/Angela/Light-dark_box/downsampled_videos/1118783_LightDarkBox_20230922_145053622downsampled_annotation_set3.npy 117
G:/Angela/Light-dark_box/downsampled_videos/1118784_LightDarkBox_20230922_150552834downsampled_annotation_set3.npy 121
G:/Angela/Light-dark_box/downsampled_videos/1118785_LightDarkBox_20230922_151852024downsampled_annotation_set3.npy 124
G:/Angela/Light-dark_box/downsampled_videos/1118786_LightDarkBox_20230922_153140038downsampled_annotation_set3.npy 116
G:/Angela/Light-dark_box/downsampled_videos/1118786_Second_LightDarkBox_20230922_153730486downsampled_annotation_set3.npy 0
G:/Angela/Light-dark_box/downsampled_videos/1118787_LightDarkBox_20230922_154756153downsampled_annotation_set3.npy 132
G:/Angela/Light-dark_box/downsampled_videos/1118790_LightDarkBox_20230922_140542869downsampled_annotation_set3.npy 119
G:/Angela/Light-dark_box/downsampled_videos/1118791_LightDarkBox_20230922_143516429downsampled_annotation_set3.npy 132
G:/Angela/Light-dark_box/downsampled_videos/1118793_LightDarkBox_20230922_163301885downsampled_annotation_set3.npy 118
G:/Angela/Light-dark_box/downsampled_videos/1118794_LightDarkBox_20230922_164545638downsampled_annotation_set3.npy 115
G:/Angela/Light-dark_box/downsampled_videos/1118795_LightDarkBox_20230922_165758380downsampled_annotation_set3.npy 101
G:/Angela/Light-dark_box/downsampled_videos/1118796_LightDarkBox_20230922_171039708downsampled_annotation_set3.npy 108
G:/Angela/Light-dark_box/downsampled_videos/1118881_Light-dark_box_20231006_151209983downsampled_annotation_set3.npy 129
G:/Angela/Light-dark_box/downsampled_videos/1118882_Light-dark_box_20231006_152502926downsampled_annotation_set3.npy 154
G:/Angela/Light-dark_box/downsampled_videos/1118883_Light-dark_box_20231006_145910220downsampled_annotation_set3.npy 133
G:/Angela/Light-dark_box/downsampled_videos/1119001_light-dark_box_20231026_153024319downsampled_annotation_set3.npy 161
G:/Angela/Light-dark_box/downsampled_videos/1119002_light-dark_box_20231030_102458042downsampled_annotation_set3.npy 151
G:/Angela/Light-dark_box/downsampled_videos/1119036_light-dark_box_20231030_113119910downsampled_annotation_set3.npy 142
G:/Angela/Light-dark_box/downsampled_videos/1119037_light-dark_box_20231030_110456567downsampled_annotation_set3.npy 154
G:/Angela/Light-dark_box/downsampled_videos/1119038_light-dark_box_20231030_111834677downsampled_annotation_set3.npy 142
G:/Angela/Light-dark_box/downsampled_videos/1119039_light-dark_box_20231030_105148130downsampled_annotation_set3.npy 144
G:/Angela/Light-dark_box/downsampled_videos/1119040_light-dark_box_20231030_114508219downsampled_annotation_set3.npy 148
G:/Angela/Light-dark_box/downsampled_videos/1119041_light-dark_box_20231030_115840402downsampled_annotation_set3.npy 152
G:/Angela/Light-dark_box/downsampled_videos/1119042_light-dark_box_20231030_121144556downsampled_annotation_set3.npy 185
G:/Angela/Light-dark_box/downsampled_videos/1119050_light-dark_box_20231030_103823635downsampled_annotation_set3.npy 142
G:/Angela/Light-dark_box/downsampled_videos/1119060_light-dark_box_20231030_122437222downsampled_annotation_set3.npy 138
G:/Angela/Light-dark_box/downsampled_videos/1119143_light-dark_box_20231120_104745557downsampled_annotation_set3.npy 154
G:/Angela/Light-dark_box/downsampled_videos/1119631_LightDarkBox_20230811_142233939downsampled_annotation_set3.npy 110
G:/Angela/Light-dark_box/downsampled_videos/1119632_LightDarkBox_20230811_122730307downsampled_annotation_set3.npy 115
G:/Angela/Light-dark_box/downsampled_videos/1119633_LightDarkBox_20230811_124022173downsampled_annotation_set3.npy 122
G:/Angela/Light-dark_box/downsampled_videos/1119636_LightDarkBox_20230811_150125724downsampled_annotation_set3.npy 109
G:/Angela/Light-dark_box/downsampled_videos/1119637_LightDarkBox_20230811_151500157downsampled_annotation_set3.npy 120
G:/Angela/Light-dark_box/downsampled_videos/1119663_LightDarkBox_20230811_111801893downsampled_annotation_set3.npy 143
G:/Angela/Light-dark_box/downsampled_videos/1119723_LightDarkBox_20230811_144859539downsampled_annotation_set3.npy 108
G:/Angela/Light-dark_box/downsampled_videos/1119724_LightDarkBox_20230811_152750589downsampled_annotation_set3.npy 122

In [3]:
test=np.load('/Users/loukia/Desktop/LocatioAnalysis/Loc_15/TrackingData/1119050_20231020_Loc_15_mousecoordx.npy')
print(test.shape)
print(type(test))
print(test)

(8, 18192)
<class 'numpy.ndarray'>
[[ 34.56  33.34  31.77 ... 504.2  504.2  504.2 ]
 [ 37.9   37.53  37.53 ... 522.5  522.5  522.5 ]
 [ 51.47  49.    47.6  ... 506.2  506.2  506.2 ]
 ...
 [ 86.8   79.06  74.8  ... 509.5  509.   508.  ]
 [   nan 101.8  101.8  ... 541.5  537.5  530.5 ]
 [   nan    nan    nan ... 467.   467.   467.  ]]

In [ ]:
test2=np.load('F:Analysis_M1115859_20210415/kilosortData/templates.npy')
print(test2.shape)
print(type(test2))
print(test2)

In [12]:
test3 = np.load('G:/Angela/OF/Features/1119565_20230627_OF_features.npy', allow_pickle=True)
print(test3.shape)
print(type(test3))
print(test3)
df = pd.DataFrame(test3)
df

(6, 18198)
<class 'numpy.ndarray'>
[['Timestamp' 0.0 0.03333333507180214 ... 606.4666748046875 606.5
  606.5333251953125]
 ['HeadVelocity' nan 10.835993344831213 ... 8.067038849228416
  8.092337920984082 8.101910485248862]
 ['centrevelocity' nan 9.640921909423298 ... 5.171675313315198
  5.283028381303786 5.340915527748767]
 ['HeadDirection' 323.5 323.5 ... 86.875 86.875 86.875]
 ['HeadAngularVelocity' nan 0.0 ... 0.125 0.0 0.0]
 ['BodyLength' 2.197265625 2.689453125 ... 2.89453125 2.869140625
  2.85546875]]

,0,1,2,3,4,5,6,7,8,9,...,18188,18189,18190,18191,18192,18193,18194,18195,18196,18197
0,Timestamp,0.0,0.033333,0.066667,0.1,0.133333,0.166667,0.2,0.233333,0.266667,...,606.233337,606.266663,606.299988,606.333313,606.366638,606.400024,606.43335,606.466675,606.5,606.533325
1,HeadVelocity,NaN,10.835993,10.826402,10.80923,10.788156,10.768608,10.757854,10.76377,10.794966,...,6.669831,7.011969,7.319322,7.577496,7.778509,7.922133,8.014552,8.067039,8.092338,8.10191
2,centrevelocity,NaN,9.640922,9.655709,9.68552,9.731392,9.794874,9.8797,9.990262,10.132255,...,3.816354,3.978647,4.172948,4.387354,4.608544,4.822447,5.014503,5.171675,5.283028,5.340916
3,HeadDirection,323.5,323.5,329.5,333.0,333.5,332.0,328.25,323.0,325.0,...,44.25,44.25,55.75,79.375,81.75,77.5,86.75,86.875,86.875,86.875
4,HeadAngularVelocity,NaN,0.0,6.0,3.5,0.5,-1.5,-3.75,-5.25,2.0,...,-1.5,0.0,11.5,6.9375,2.375,-4.25,9.25,0.125,0.0,0.0
5,BodyLength,2.197266,2.689453,2.882812,2.726562,2.669922,2.710938,2.837891,2.794922,2.488281,...,2.488281,2.488281,2.277344,2.556641,2.683594,2.837891,2.927734,2.894531,2.869141,2.855469

In [4]:
test4=np.load('G:/Angela/EPM/TrackingData/1118777_20230911_EPM_boxcoord.npy', allow_pickle=True)
print(test4.shape)
print(type(test4))
print(test4)
df2 = pd.DataFrame(test4)
df2

(12, 2)
<class 'numpy.ndarray'>
[[ 551.  118.]
 [ 689.  118.]
 [ 547.  408.]
 [ 688.  410.]
 [ 546.  549.]
 [ 687.  553.]
 [ 545.  846.]
 [ 682.  848.]
 [ 224.  407.]
 [ 224.  545.]
 [1009.  414.]
 [1009.  551.]]

         0      1
0    551.0  118.0
1    689.0  118.0
2    547.0  408.0
3    688.0  410.0
4    546.0  549.0
5    687.0  553.0
6    545.0  846.0
7    682.0  848.0
8    224.0  407.0
9    224.0  545.0
10  1009.0  414.0
11  1009.0  551.0